defmodule CatalystWeb.Endpoint do
  # Desktop.Endpoint is a thin wrapper over Phoenix.Endpoint that integrates
  # with the elixir-desktop webview. It works as a normal Phoenix endpoint in
  # the browser too (used for fast dev), and `Desktop.Auth` (added below, only
  # outside code-reloading) locks the packaged app down to the webview.
  use Desktop.Endpoint, otp_app: :catalyst_web

  # Desktop.Endpoint 1.5 still generates a Ranch-specific dynamic-port lookup
  # outside Phoenix 1.7. Phoenix 1.8 exposes server_info/1, which works with
  # the configured Bandit adapter and avoids adding Cowboy/Ranch just for this.
  defoverridable get_dynamic_port: 1

  def get_dynamic_port(scheme) do
    {:ok, {_ip, port}} = server_info(scheme)
    port
  end

  # In desktop mode the webview does not reliably persist cookies, so the
  # session is held in an ETS table (the `:session` table created in
  # CatalystWeb.Application before the endpoint starts).
  @session_options [
    store: :ets,
    key: "_catalyst_key",
    table: :session
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :catalyst_web,
    gzip: not code_reloading?,
    only: CatalystWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Restrict access to the locally-bound webview in packaged builds: Desktop.Auth
  # checks the `?k=` token the window injects. Compiled in only for :prod so the
  # app stays reachable from a browser in dev and from LiveView tests.
  if Mix.env() == :prod do
    plug Desktop.Auth
  end

  plug CatalystWeb.Router
end
